export const BANCOS_CONHECIDOS: Record<string, string[]> = {
  "AGI": ["Repasse_Recibos_Agenciamento_"],
  "AKI": ["AKI"],
  "AMIGOZ": ["AMIGOZ"],
  "BRB360": ["BRB360"],
  "BRBRED": ["BRBRED"],
  "BRB": ["BRB"],
  "BTW": ["BTW"],
  "BV": ["BV"],
  "C6 BANK": ["C6", "ANALÍTICO KGIRO", "C6AUTO"],
  "CAIXA": ["CAIXA"],
  "CAPITALCONSIG": ["CAPITALCONSIG", "CAPITAL CONSIG"],
  "CASHCARD": ["CASHCARD"],
  "CREDITAS": ["CREDITAS"],
  "CREFISA": ["CREFISA"],
  "COMISSAO ZERADA": ["FIX_TABELAS_ZERADAS_", "COMISSAOZERADA PORT", "COMISSAOZERADA (SUB INDICADO BANCO)", "INDICADOSUB BANCO", "PORT ZERADA"],
  "DAYCOVAL": ["DAYCOVAL"],
  "DIGIO": ["DIGIO"],
  "EMPRESTEI CRED": ["EMPRESTEI CRED"],
  "EURO": ["EURO"],
  "EVOL": ["EVOL"],
  "FACTA": ["FACTA"],
  "FIT_SANTANDER": ["FIT_SANTANDER"],
  "GRANDINO": ["GRANDINO"],
  "HAPPY": ["HAPPY"],
  "HOPE": ["HOPE"],
  "ICRED": ["ICRED"],
  "JBCRED": ["JBCRED"],
  "KARDBANK": ["KARDBANK", "FECHAMENTO"],
  "MASTER": ["MASTER"],
  "MERCANTIL": ["MERCANTIL"],
  "NBC": ["NBC"],
  "NEO": ["NEO"],
  "NOVOSAQUE": ["NOVOSAQUE"],
  "NYC": ["NYC"],
  "OLE": ["OLE"],
  "PAN": ["PAN"],
  "PAN LAFY": ["PAN LAFY"],
  "PARANABANK": ["PARANABANK"],
  "PHTECH": ["PHTECH"],
  "PRESENCA": ["PRESENCA"],
  "QUALIBANK": ["QUALIBANK"],
  "QUERO MAIS": ["QUERO MAIS", "QUEROMAISCOMISSAO", "QUERO+_CANCELAMENTO"],
  "SAFRA": ["SAFRA"],
  "SANTANDER": ["SANTANDER"],
  "SEGURO FVE": ["SEGURO FVE"],
  "SEGURO WL": ["SEGURO WL"],
  "TOTALCASH": ["TOTALCASH"],
  "V8": ["V8"],
  "VCTEX": ["VCTEX "],
  "VIA CERTA": ["VIA CERTA"],
  "WEBCASH": ["WEBCASH"]
};

export const BANCOS_MAIS_LOJAS = [
  "FACTA FINANCEIRA", "OLE", "BMG", "C6 BANK", "C6", "DAYCOVAL", "MERCANTIL", "NOVOSAQUE", "PAN", "QUERO MAIS", "SAFRA", "VCTEX", "CREFAZ"
]

export const times_for_week = {
  "AGI": 1,
  'AKI': 5,
  'AMIGOZ': 2,
  'BANRISUL': 5,
  'BMG_34362_BMG_CARD_ATO_E_DIFERIDO_CONSOLIDADO': 5,
  'BMG_34362_CARTAO_BENEFICIO_ATO_E_DIFERIDO_CONSOLIDADO': 5,
  'BMG_34362_CONSIGNADO_ATO_E_DIFERIDO_CONSOLIDADO': 5,
  'BMG_34362_ROTATIVO_CONSOLIDADO': 5,
  'BMG_34362_SALDOPAGOCARD': 5,
  'BMG_34362_SALDOPAGOCARTAOBENEFICIO': 5,
  'BMG_34362_SAQUE_FGTS_ATO_E_DIFERIDO_CONSOLIDADO': 5,
  'BMG_34362_SEGURO_ATO_CONSOLIDADO': 5,
  'BMG_53259_BMG_CARD_ATO_E_DIFERIDO_CONSOLIDADO': 5,
  'BMG_53259_CARTAO_BENEFICIO_ATO_E_DIFERIDO_CONSOLIDADO': 5,
  'BMG_53259_CONSIGNADO_ATO_E_DIFERIDO_CONSOLIDADO': 5,
  'BMG_53259_SALDOPAGOCARD': 5,
  'BMG_53259_SALDOPAGOCARTAOBENEFICIO': 5,
  'BMG_53259_SAQUE_FGTS_ATO_E_DIFERIDO_CONSOLIDADO': 5,
  'BMG_53259_SEGURO_ATO_CONSOLIDADO': 5,
  'BRB': 1,
  'BRB360': 2,
  'BRBRED': 1,
  'BTW': 1,
  'BV': 1,
  'C6_ANALÍTICO COMISSÃO FLAT (AUTOMÁTICO + MANUAL (C+D))': 5,
  'C6_ANALÍTICO KGIRO': 1,
  'C6_C6AUTO': 1,
  'C6_C6 AUTO ZERADO - COMISSÃO À VISTA - ANALÍTICO': 1,
  'C6_C6EQUITY': 1,
  'CAIXA': 1,
  'CAPITALCONSIG': 1,
  'CASHCARD': 5,
  'COMISSAO ZERADA': 1,
  'CREFAZ_CLT CREFAZ': 5,
  'CREFAZ_CREFAZ': 5,
  'CREFISA': 5,
  'DAYCOVAL': "",
  'DAYCOVAL_AUTORREGULAÇÃO': 1,
  'DAYCOVAL_CARTÃO RELATORIOCOMISSAO': 5,
  'DAYCOVAL_CONSIGNADO COMISSOES A RECEBER': 5,
  'DAYCOVAL_EXERCITO CARTÃO RELATORIOCOMISSAO': 1,
  'DAYCOVAL_EXERCITO CONSIGNADO COMISSOES A RECEBER': 5,
  'DAYCOVAL_PRESTAMISTA': 2,
  'DAYCOVAL_PRESTAMISTA DIAMANTE': 2,
  'DIGIO': 5,
  'EMPRESTEI CRED': 1,
  'EURO': 1,
  'EVOL': 5,
  'FACTA_LEV': 5,
  'FACTA_WL': 5,
  'FIT_SANTANDER': 1,
  'GRANDINO': 5,
  'HAPPY': 1,
  'HOPE': 5,
  'ICRED': 5,
  'ITAU': 5,
  'JBCRED': 1,
  'KARDBANK': 2,
  'MASTER': 0,
  'MERCANTIL': 0,
  'MERCANTIL_BMB-DIARIO-COMISSAO-AVISTA': 5,
  'MERCANTIL_BMB-DIARIO-COMISSAO-PARCELADO': 5,
  'MERCANTIL_MBF-DIARIO-COMISSAO-PARCELADO': 1,
  'MERCANTIL_BMB-SEMANAL-PRODUCAO': 1,
  'MERCANTIL_MBF-SEMANAL-PRODUCAO': 1,
  'MERCANTIL_RELATORIO_TARIFA_-_LEV_INTERMEDIACAO': 1,
  'NBC': 1,
  'NEO': 1,
  'NOVOSAQUE': 0,
  'NOVOSAQUE_NOVOSAQUE': 5,
  'NOVOSAQUE_NOVOSAQUE CLT': 5,
  'NYC': 5,
  'OLE': 0,
  'OLE_OLE_FVE': 5,
  'OLE_OLE WL': 5,
  'OUTROS': 1,
  'PAN': 0,
  'PAN_2907_DEMONSTRATIVO': 1,
  'PAN_2907_RELCOMISSAO': 5,
  'PAN_2907_RELCOMISSAOCARTAO': 5,
  'PAN_3987_RELCOMISSAO': 5,
  'PAN_3987_RELCOMISSAOCARTAO': 5,
  'PAN_4336_RELCOMISSAO': 5,
  'PAN_4336_RELCOMISSAOCARTAO': 5,
  'PAN LAFY': 5,
  'PARANABANK': 5,
  'PHTECH': 5,
  'PRESENCA': 5,
  'QUALIBANK': 2,
  'QUERO MAIS': 0,
  'QUERO MAIS_QUERO MAIS': 1,
  'QUERO MAIS_QUERO MAIS CARTAO': 1,
  'QUERO MAIS_QUERO+_CANCELAMENTO': 1,
  'SABEMI': 5,
  'SAFRA': 0,
  'SAFRA_CONSULTA COMISSOES - DATA PAGAMENTO - NOVO': 5,
  'SAFRA_GESTÃO CORBAN - DÉBITOS REALIZADOS': 5,
  'SAFRA_PLUS - CONSULTA COMISSOES - DATA PAGAMENTO - NOVO': 5,
  'SAFRA_PLUS - GESTÃO CORBAN - DÉBITOS REALIZADOS': 5,
  'SAFRA_PLUS - SAFRACOMISSAOZERO': 5,
  'SAFRA_SAFRACOMISSAOZERO': 5,
  'SANTANDER': 5,
  'TOTALCASH': 2,
  'V8': 5,
  'VCTEX': 0,
  'VCTEX_VCTEX NOVA LEV': 5,
  'VCTEX_VCTEX WL': 5,
  'VIA CERTA': 1,
  'WEBCASH': 1,
}

export const times_for_day = {
  "ANCORA": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "AKI CAPITAL": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "AMIGOZ": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 1,
  },
  "BANRISUL": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "BMG": {
    "Segunda": "min 10 max 13",
    "Terça": "min 10 max 13",
    "Quarta": "min 10 max 13",
    "Quinta": "min 10 max 13",
    "Sexta": "min 10 max 13",
  },
  "BRB - 360": {
    "Segunda": 0,
    "Terça": 1,
    "Quarta": 0,
    "Quinta": 1,
    "Sexta": 0,
  },
  "BRB - INCONTA": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 0,
    "Quinta": 0,
    "Sexta": 1,
  },
  "BRB - RED": {
    "Segunda": "dia 15 ou 30",
    "Terça": "dia 15 ou 30",
    "Quarta": "dia 15 ou 30",
    "Quinta": "dia 15 ou 30",
    "Sexta": "dia 15 ou 30",
  },
  "BTG PACTUAL": {
    "Segunda": "Manual",
    "Terça": "Manual",
    "Quarta": "Manual",
    "Quinta": "Manual",
    "Sexta": "Manual",
  },
  "BTW BANK": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "BV": {
    "Segunda": "Manual",
    "Terça": "Manual",
    "Quarta": "Manual",
    "Quinta": "Manual",
    "Sexta": "Manual",
  },
  "C6 AUTO": {
    "Segunda": 1,
    "Terça": 0,
    "Quarta": 0,
    "Quinta": 0,
    "Sexta": 0,
  },
  "C6 BANK": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "C6 EQUITY": {
    "Segunda": 1,
    "Terça": 0,
    "Quarta": 0,
    "Quinta": 0,
    "Sexta": 0,
  },
  "CAIXA": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 0,
    "Quinta": 0,
    "Sexta": 0,
  },
  "CAPITAL CONSIG": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "CREDITAS": {
    "Segunda": "Manual",
    "Terça": "Manual",
    "Quarta": "Manual",
    "Quinta": "Manual",
    "Sexta": "Manual",
  },
  "CREFAZ": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "CREFISA": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 1,
  },
  "DAYCOVAL": {
    "Segunda": 2,
    "Terça": 2,
    "Quarta": 2,
    "Quinta": 2,
    "Sexta": 2,
  },
  "DIGIO": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "EMPRESTEI CARD": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "EURO": {
    "Segunda": 0,
    "Terça": 1,
    "Quarta": 0,
    "Quinta": 0,
    "Sexta": 0,
  },
  "EVOL": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "FACTA FINANCEIRA": {
    "Segunda": 2,
    "Terça": 2,
    "Quarta": 2,
    "Quinta": 2,
    "Sexta": 2,
  },
  "FIT ENERGIA": {
    "Segunda": "mes 1",
    "Terça": "mes 1",
    "Quarta": "mes 1",
    "Quinta": "mes 1",
    "Sexta": "mes 1",
  },
  "GRANDINO BANK": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "HAPPY": {
    "Segunda": 0,
    "Terça": 1,
    "Quarta": 0,
    "Quinta": 1,
    "Sexta": 0,
  },
  "HOPE": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "ICRED": {
    "Segunda": 2,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "JBCRED": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 0,
  },
  "KARDBANK": {
    "Segunda": 2,
    "Terça": 0,
    "Quarta": 0,
    "Quinta": 2,
    "Sexta": 0,
  },
  "MASTER": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "MERCANTIL": {
    "Segunda": "min 2 max 4",
    "Terça": "min 2 max 4",
    "Quarta": "min 2 max 4",
    "Quinta": "min 2 max 4",
    "Sexta": "min 2 max 4",
  },
  "MEUCASHCARD": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "NEO CREDITO": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 0,
  },
  "NOVO SAQUE": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "NYC BANK": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "PAN": {
    "Segunda": 3,
    "Terça": 3,
    "Quarta": 3,
    "Quinta": 3,
    "Sexta": 3,
  },
  "PAN LAFY": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "PARANA BANK": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "PH TECH": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "PRESENCA BANK": {
    "Segunda": "Manual",
    "Terça": "Manual",
    "Quarta": "Manual",
    "Quinta": "Manual",
    "Sexta": "Manual",
  },
  "QUALI BANK": {
    "Segunda": 1,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 0,
  },
  "QUERO MAIS CREDITO": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "RODOBENS": {
    "Segunda": "Manual",
    "Terça": "Manual",
    "Quarta": "Manual",
    "Quinta": "Manual",
    "Sexta": "Manual",
  },
  "SABEMI": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "SAFRA": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "SANTANDER": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "OLE": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "TOTALCASH": {
    "Segunda": 0,
    "Terça": 1,
    "Quarta": 0,
    "Quinta": 1,
    "Sexta": 0,
  },
  "V8 DIGITAL": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  },
  "VCTEX": {
    "Segunda": 2,
    "Terça": 2,
    "Quarta": 2,
    "Quinta": 2,
    "Sexta": 2,
  },
  "WEBCASH": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 0,
  },
  "SEGURO": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 0,
  },
  "OUTROS": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 0,
  },
}

export const banks = [
  'AKI', 
  'AMIGOZ', 
  'BANRISUL',
  'BMG',
  'BRB360',
  'BRBINCONTA',
  'BRBRED',
  'BTG PACTUAL',
  'BTW',
  'BV',
  'C6 AUTO',
  'C6EQUITY',
  'C6 BANK',
  'CAIXA',
  'CAPITALCONSIG',
  'CREDITAS',
  'CREFAZ',
  'CREFISA',
  'DAYCOVAL',
  'DIGIO',
  'EMPRESTEI',
  'EURO',
  'EVOL',
  'FACTA',
  'FIT ENERGIA',
  'GRANDINO',
  'HAPPY',
  'HOPE',
  'ICRED',
  'JBCRED',
  'KARDBANK',
  'MASTER',
  'MERCANTIL',
  'CASHCARD',
  'NEO',
  'NOVOSAQUE',
  'NYC',
  'PAN',
  'PANLAFY',
  'PARANABANK',
  'PHTECH',
  'PRESENCA',
  'QUALIBANK',
  'QUERO MAIS',
  'RODOBENS',
  'SABEMI',
  'SAFRA',
  'SANTANDER',
  'OLE',
  'TOTALCASH',
  'V8',
  'VCTEX',
  'WEBCASH',
  'BRB_LOJA_LHAMAS',
  'SEGURO'
]