export const BANCOS_CONHECIDOS = [
  "ICRED", "EURO", "HOPE", "V8", "NYC", "GRANDINO", "AKI", "CREFISA",
  "PAN", "PHTECH", "BRB", "HAPPY", "SAFRA", "CASHCARD", "DIGIO",
  "VCTEX", "NOVOSAQUE", "PARANABANK", "EVOL", "OLE", "SANTANDER",
  "QUERO MAIS", "WEBCASH", "KARDBANK", "AMIGOZ", "CAPITALCONSIG",
  "QUALIBANK", "FACTA", "JBCRED", "DAYCOVAL", "MASTER", "MERCANTIL", "VIA CERTA",
  "C6", "TOTALCASH", "SEGURO FVE", "SEGURO WL", "PRESENCA"
];

export const BANCOS_MAIS_LOJAS = [
    "FACTA", "OLE", "BMG", "C6 BANK", "C6", "DAYCOVAL", "MERCANTIL", "NOVOSAQUE", "PAN", "QUERO MAIS", "SAFRA", "VCTEX"
]
