export function generateLast30Days() {
  const dates = [];
  for (let i = 0; i < 30; i++) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    dates.push(d.toISOString().split('T')[0]);
  }
  return dates;
};

const map: Record<string, string> = {
  "Aki": "AKI CAPITAL",
  "Amigoz": "AMIGOZ",
  "Bmg Bonus 34362": "BMG 34362",
  "Bmg Cartao Beneficio 34362": "BMG 34362",
  "Bmg Saldo 34362": "BMG 34362",
  "Bmg Seguro 34362": "BMG 34362",
  "Bmg Bonus 53259": "BMG 53259",
  "Bmg Cartao Beneficio 53259": "BMG 53259",
  "Bmg Saldo 53259": "BMG 53259",
  "Bmg Seguro 53259": "BMG 53259",
  "BRB 360": "BRB 360",
  "BRB Inconta Validar": "BRB INCONTA",
  "BRB Red": "BRB RED",
  "BTW": "BTW",
  // "Bv": "BV",
  "C6 Auto": "C6 AUTO",
  "C6 bank Comissao": "C6 BANK",
  "C6 Equity": "C6 CAR EQUITY",
  "C6 Kgiro": "KGIRO",
  "Caixa": "CBA - CAIXA",
  "CAPITAL CONSIG Cancelados": "CAPITAL CONSIG",
  "CAPITAL CONSIG Comissao": "CAPITAL CONSIG",
  "CAPITAL CONSIG Seguro": "CAPITAL CONSIG",
  // "ComissaoZerada": "OUTROS",
  "Crefaz": "CREFAZ",
  "Crefaz CLT": "CREFAZ CLT",
  // "CrefisaJN": "CREFISA JN",
  // "CrefisaWL": "CREFISA WL",
  "Daycoval Cartao": "DAYCOVAL CARTÃO",
  "Daycoval Cartao EX": "DAYCOVAL CARTÃO EX",
  "Daycoval Consig": "DAYCOVAL CONSIG",
  "Daycoval Consig EX": "DAYCOVAL CONSIG EX",
  "Digio": "DIGIO",
  "EmpresteiCred": "EMPRESTEI CRED",
  "Euro": "EURO 17",
  "Evol": "EVOL",
  // "Facta": "FACTA",
  "Grandino": "GRANDINO",
  "Happy": "HAPPY",
  "Hope": "HOPE",
  "Icred": "ICRED",
  // "Itau360": "ITAU 360",
  // "ItauConsig": "ITAU CONSIG",
  "Jbcred": "JBCRED",
  "Kardbank": "KARDBANK",
  // "MASTER": "MASTER",
  "MEUCASHCARD": "MEUCASHCARD",
  "NBC": "NBC",
  "NEO": "NEO",
  "Novo Saque": "NOVO SAQUE",
  "Novo Saque Cartao": "NOVO SAQUE",
  "NYC": "NYC",
  "Parana Bank": "PARANÁ BANK",
  "PAN Cartao WL": "PAN WL",
  "PAN Cartao LEV": "PAN LEV",
  "PAN Cartao PLUS": "PAN PLUS",
  "PAN Consig WL": "PAN WL",
  "PAN Consig LEV": "PAN LEV",
  "PAN Consig PLUS": "PAN PLUS",
  "PAN LAFY": "PAN LAFY",
  "PHtech": "PH TECH",
  "Presenca": "PRESENÇA BANK",
  "QualiBank": "QUALIBANK",
  "Quero Mais Cartao": "QUERO CARTÃO",
  // "QUERO CARTÃO": "",
  "Quero Mais Consig": "QUERO CONSIG",
  "Sabemi": "SABEMI",
  "Safra Comissao Zero CBU": "SAFRA CBU (37)",
  "Safra Comissao Zero CBSU": "SAFRA CBSU (72)",
  "Safra Debitos CBU": "SAFRA CBU (37)",
  "Safra Debitos CBSU": "SAFRA CBSU (72)",
  "Safra Pagamento Novo CBU": "SAFRA CBU (37)",
  "Safra Pagamento Novo CBSU": "SAFRA CBSU (72)",
  "Santander Fit": "SANTANDER FIT ENERG",
  "Santander FVEVI": "SANTANDER FVE",
  "OLE_FVE": "SANTANDER OLE",
  "Total Cash": "TOTAL CASH",
  "V8": "V8",
  "VCtex NOVA": "VCTEX NOVA LEV",
  "VCtex WL": "VCTEX WL",
  // "Viacerta": "",
  "WebCash": "WEBCASH",
}

export async function findBank(bank: string): Promise<string> {

  try {
    const getBank: string = map[bank] ?? "Banco não localizado";
    return getBank
  } catch (error) {
    console.error(error)
    return "error"
  }

}

export function extractFilename(disposition: string | null) {
  if (!disposition) return null;
  const matches = /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/.exec(disposition);
  return matches && matches[1] ? decodeURIComponent(matches[1].replace(/['"]/g, '')) : null;
}

export const bank_id = {
  "DIGIO": 15,
  "EMPRESTEI CRED": 16,
  "EURO 17": 17,
  "EVOL": 18,
  "FACTA 92359": 62,
  "GRANDINO": 19,
  "HAPPY": 20,
  "HOPE": 21,
  "ICRED": 22,
  "ITAU 360": 24,
  "ITAU CONSIG": 23,
  "AKI CAPITAL": 2,
  "AMIGOZ": 1,
  "AMIGOZ TEDDY": 3,
  "BANRISUL": 60,
  "BMG": 55,
  "BRB 360": 5,
  "BRB INCONTA": 6,
  "BRB RED": 4,
  "BTW": 9,
  "C6 BANK": 8,
  "C6 CAR EQUITY": 10,
  "CAPITAL CONSIG": 11,
  "CBA - CAIXA": 12,
  "JBCRED": 25,
  "KARDBANK": 26,
  "KGIRO": 53,
  "MASTER": 27,
  "MEUCASHCARD": 28,
  "NEO": 59,
  "NOVO SAQUE": 29,
  "NOVO SAQUE CLT": 52,
  "NYC": 30,
  "PAN LAFY": 42,
  "PAN LEV": 40,
  "PAN PLUS": 41,
  "PAN WL": 31,
  "PARANÁ BANK": 32,
  "PARANÁ BANK - SEGURO": 50,
  "PH TECH": 33,
  "PRESENÇA BANK": 34,
  "QUALIBANK": 35,
  "QUERO CARTÃO": 47,
  "QUERO CONSIG": 36,
  "SABEMI": 37,
  "SAFRA CBSU (72)": 46,
  "SAFRA CBU (37)": 38,
  "SANTANDER FIT ENERG": 58,
  "SANTANDER FVE": 56,
  "SANTANDER OLE": 57,
  "TOO SEGUROS LEV": 54,
  "TOO SEGUROS WL": 51,
  "TOTAL CASH": 7,
  "V8": 44,
  "VCTEX NOVA LEV": 39,
  "VCTEX WL": 43,
  "WEBCASH": 45,
  "DAYCOVAL CARTÃO": 63,
  "DAYCOVAL CONSIG EX": 64,
  "DAYCOVAL CARTÃO EX": 65,
  "FACTA 94569": 66,
  "CREFAZ": 13,
  "CREFAZ CLT": 48,
  "CREFISA JN": 14,
  "CREFISA WL": 49,
  "DAYCOVAL CONSIG": 61,
}