export function generateLast30Days() {
  const dates = [];
  for (let i = 0; i < 30; i++) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    dates.push(d.toISOString().split('T')[0]);
  }
  return dates; // Retorna [hoje, ontem, anteontem...]
};

const map: Record<string, string> = {
  "Aki": "AKI CAPITAL",
  "Amigoz": "AMIGOZ",
  "BRB360": "BRB 360",
  "BRBInconta Validar": "BRB INCONTA",
  "BRBRed": "BRB RED",
  "BTW": "BTW",
  // "Bv": "BV",
  "C6Auto": "C6 AUTO",
  "C6bankComissao": "C6 BANK",
  "C6Equity": "C6 CAR EQUITY",
  "Caixa": "CBA - CAIXA",
  "CAPITALCONSIGCancelados": "CAPITAL CONSIG",
  "CAPITALCONSIGComissao": "CAPITAL CONSIG",
  "CAPITALCONSIGSeguro": "CAPITAL CONSIG",
  // "ComissaoZerada": "OUTROS",
  // "Crefaz": "CREFAZ",
  // "CrefazCLT": "CREFAZ CLT",
  // "CrefisaJN": "CREFISA JN",
  // "CrefisaWL": "CREFISA WL",
  "Digio": "DIGIO",
  "EmpresteiCred": "EMPRESTEI CRED",
  "Euro": "EURO 17",
  "Evol": "EVOL",
  // "Facta": "FACTA",
  "Grandino": "GRANDINO",
  "Happy": "HAPPY",
  "Hope": "HOPE",
  "Icred": "ICRED",
  // "Itau360": "ITAU 360",
  // "ItauConsig": "ITAU CONSIG",
  "Jbcred": "JBCRED",
  "Kardbank": "KARDBANK",
  // "KGIRO": "KGIRO",
  // "MASTER": "MASTER",
  "MEUCASHCARD": "MEUCASHCARD",
  // "NBC": "",
  // "NEO": "",
  "NovoSaque": "NOVO SAQUE",
  "NovoSaqueCF": "NOVO SAQUE",
  "NovoSaqueCartao": "NOVO SAQUE",
  "NYC": "NYC",
  "ParanaBank": "PARANÁ BANK",
  "PANLAFY": "PAN LAFY",
  "PHtech": "PH TECH",
  "Presenca": "PRESENÇA BANK",
  "QualiBank": "QUALIBANK",
  // "QUERO CARTÃO": "",
  // "QUERO CONSIG": "",
  // "SABEMI": "",
  "SafraComissaoZeroCBU": "SAFRA CBU (37)",
  "SafraComissaoZeroCBSU": "SAFRA CBSU (72)",
  "SantanderFit": "SANTANDER FIT ENERG",
  "SantanderFVEVI": "SANTANDER FVE",
  "OLE_FVE": "SANTANDER OLE",
  "TotalCash": "TOTAL CASH",
  "V8": "V8",
  "VCtexNOVA": "VCTEX NOVA LEV",
  "VCtexWL": "VCTEX WL",
  // "Viacerta": "",
  "WebCash": "WEBCASH",
}

export async function findBank(bank: string): Promise<string> {

  try {
    const getBank: string = map[bank] ?? "Banco não localizado";
    return getBank
  } catch (error) {
    console.error(error)
    return "error"
  }

}

export function extractFilename(disposition: string | null) {
  if (!disposition) return null;
  const matches = /filename[^;=\n]*=((['"]).*?\2|[^;\n]*)/.exec(disposition);
  return matches && matches[1] ? decodeURIComponent(matches[1].replace(/['"]/g, '')) : null;
}

export const times_for_day = [
  {"AKI CAPITAL": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"AMIGOZ": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 1,
  }},
  {"BANRISUL": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"BMG": {
    "Segunda": "min 10 max 13",
    "Terça": "min 10 max 13",
    "Quarta": "min 10 max 13",
    "Quinta": "min 10 max 13",
    "Sexta": "min 10 max 13",
  }},
  {"BRB - 360": {
    "Segunda": 0,
    "Terça": 1,
    "Quarta": 0,
    "Quinta": 1,
    "Sexta": 0,
  }},
  {"BRB - INCONTA": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 0,
    "Quinta": 0,
    "Sexta": 1,
  }},
  {"BRB - RED": {
    "Segunda": "dia 15 ou 30",
    "Terça": "dia 15 ou 30",
    "Quarta": "dia 15 ou 30",
    "Quinta": "dia 15 ou 30",
    "Sexta": "dia 15 ou 30",
  }},
  {"BTG PACTUAL": {
    "Segunda": "Manual",
    "Terça": "Manual",
    "Quarta": "Manual",
    "Quinta": "Manual",
    "Sexta": "Manual",
  }},
  {"BTW BANK": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"BV": {
    "Segunda": "Manual",
    "Terça": "Manual",
    "Quarta": "Manual",
    "Quinta": "Manual",
    "Sexta": "Manual",
  }},
  {"C6 AUTO": {
    "Segunda": 1,
    "Terça": 0,
    "Quarta": 0,
    "Quinta": 0,
    "Sexta": 0,
  }},
  {"C6 BANK": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"CAIXA": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 0,
    "Quinta": 0,
    "Sexta": 0,
  }},
  {"CAPITAL CONSIG": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"CREDITAS": {
    "Segunda": "Manual",
    "Terça": "Manual",
    "Quarta": "Manual",
    "Quinta": "Manual",
    "Sexta": "Manual",
  }},
  {"CREFAZ": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"CREFISA": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 1,
  }},
  {"DAYCOVAL": {
    "Segunda": 2,
    "Terça": 2,
    "Quarta": 2,
    "Quinta": 2,
    "Sexta": 2,
  }},
  {"DIGIO": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"EMPRESTEI CARD": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"EURO": {
    "Segunda": 0,
    "Terça": 1,
    "Quarta": 0,
    "Quinta": 0,
    "Sexta": 0,
  }},
  {"EVOL": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"FACTA FINANCEIRA": {
    "Segunda": 2,
    "Terça": 2,
    "Quarta": 2,
    "Quinta": 2,
    "Sexta": 2,
  }},
  {"FIT ENERGIA": {
    "Segunda": "mes 1",
    "Terça": "mes 1",
    "Quarta": "mes 1",
    "Quinta": "mes 1",
    "Sexta": "mes 1",
  }},
  {"GRANDINO BANK": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"HOPE": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"ICRED": {
    "Segunda": 2,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"JBCRED": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 0,
  }},
  {"KARDBANK": {
    "Segunda": 2,
    "Terça": 0,
    "Quarta": 0,
    "Quinta": 2,
    "Sexta": 0,
  }},
  {"MERCANTIL": {
    "Segunda": "min 2 max 4",
    "Terça": "min 2 max 4",
    "Quarta": "min 2 max 4",
    "Quinta": "min 2 max 4",
    "Sexta": "min 2 max 4",
  }},
  {"MEUCASHCARD": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"NEO CREDITO": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 0,
  }},
  {"NOVO SAQUE": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"NYC BANK": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"PAN": {
    "Segunda": 3,
    "Terça": 3,
    "Quarta": 3,
    "Quinta": 3,
    "Sexta": 3,
  }},
  {"PAN LAFY": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"PARANA BANCO": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"PH TECH": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"PRESENCA BANK": {
    "Segunda": "Manual",
    "Terça": "Manual",
    "Quarta": "Manual",
    "Quinta": "Manual",
    "Sexta": "Manual",
  }},
  {"QUALI BANK": {
    "Segunda": 1,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 0,
  }},
  {"QUERO MAIS CREDITO": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"RODOBENS": {
    "Segunda": "Manual",
    "Terça": "Manual",
    "Quarta": "Manual",
    "Quinta": "Manual",
    "Sexta": "Manual",
  }},
  {"SABEMI": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"SAFRA": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"SANTANDER": {
    "Segunda": 2,
    "Terça": 2,
    "Quarta": 2,
    "Quinta": 2,
    "Sexta": 2,
  }},
  {"TOTALCASH": {
    "Segunda": 0,
    "Terça": 1,
    "Quarta": 0,
    "Quinta": 1,
    "Sexta": 0,
  }},
  {"V8 DIGITAL": {
    "Segunda": 1,
    "Terça": 1,
    "Quarta": 1,
    "Quinta": 1,
    "Sexta": 1,
  }},
  {"VCTEX": {
    "Segunda": 2,
    "Terça": 2,
    "Quarta": 2,
    "Quinta": 2,
    "Sexta": 2,
  }},
  {"WEBCASH": {
    "Segunda": 0,
    "Terça": 0,
    "Quarta": 1,
    "Quinta": 0,
    "Sexta": 0,
  }},
]

export const bank_id = {
  "DIGIO": 15, 
  "EMPRESTEI CRED": 16, 
  "EURO 17": 17, 
  "EVOL": 18, 
  "FACTA 92359": 62, 
  "GRANDINO": 19, 
  "HAPPY": 20, 
  "HOPE": 21, 
  "ICRED": 22, 
  "ITAU 360": 24, 
  "ITAU CONSIG": 23, 
  "AKI CAPITAL": 2, 
  "AMIGOZ": 1, 
  "AMIGOZ TEDDY": 3, 
  "BANRISUL": 60, 
  "BMG": 55, 
  "BRB 360": 5, 
  "BRB INCONTA": 6, 
  "BRB RED": 4, 
  "BTW": 9,
  "C6 BANK": 8, 
  "C6 CAR EQUITY": 10, 
  "CAPITAL CONSIG": 11, 
  "CBA - CAIXA": 12, 
  "JBCRED": 25, 
  "KARDBANK": 26, 
  "KGIRO": 53, 
  "MASTER": 27, 
  "MEUCASHCARD": 28, 
  "NEO": 59, 
  "NOVO SAQUE": 29, 
  "NOVO SAQUE CLT": 52, 
  "NYC": 30, 
  "PAN LAFY": 42, 
  "PAN LEV": 40, 
  "PAN PLUS": 41, 
  "PAN WL": 31, 
  "PARANÁ BANK": 32, 
  "PARANÁ BANK - SEGURO": 50, 
  "PH TECH": 33, 
  "PRESENÇA BANK": 34, 
  "QUALIBANK": 35, 
  "QUERO CARTÃO": 47, 
  "QUERO CONSIG": 36, 
  "SABEMI": 37, 
  "SAFRA CBSU (72)": 46, 
  "SAFRA CBU (37)": 38, 
  "SANTANDER FIT ENERG": 58, 
  "SANTANDER FVE": 56, 
  "SANTANDER OLE": 57, 
  "TOO SEGUROS LEV": 54, 
  "TOO SEGUROS WL": 51, 
  "TOTAL CASH": 7, 
  "V8": 44,
  "VCTEX NOVA LEV": 39,
  "VCTEX WL": 43,
  "WEBCASH": 45,
  "DAYCOVAL CARTÃO": 63,
  "DAYCOVAL CONSIG EX": 64,
  "DAYCOVAL CARTÃO EX": 65,
  "FACTA 94569": 66,
  "CREFAZ": 13,
  "CREFAZ CLT": 48,
  "CREFISA JN": 14,
  "CREFISA WL": 49,
  "DAYCOVAL CONSIG": 61,
}